<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */

function helloworld_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'contact_message_feedback_form') {
  $form['actions']['preview']['#access'] = FALSE;
  	$form['actions']['submit']['#value'] = 'SUBMIT';
  	$form['field_email']['widget']['0']['value']['#placeholder'] = 'Email';
  	$form['field_email']['widget']['0']['value']['#title'] = FALSE;
  	$form['field_name']['widget']['0']['value']['#placeholder'] = 'Name';
  	$form['field_name']['widget']['0']['value']['#title'] = FALSE;
  	$form['subject']['widget']['0']['value']['#placeholder'] = 'Subject';
  	$form['subject']['widget']['0']['value']['#required'] = 0;
  	$form['subject']['widget']['0']['value']['#title'] = FALSE;
  	$form['message']['widget']['0']['value']['#placeholder'] = 'Your Message';
  	$form['message']['widget']['0']['value']['#required'] = 0;
  	$form['message']['widget']['0']['value']['#title'] = FALSE;
  	//$form['message']['widget']['0']['value']['#placeholder'] = 'Your Message';
// dsm($form);
}
  




//   if ($form_id == 'user_login_form') {
//   	$form['name']['#attributes']['placeholder'] = 'test';
// }
  






  if ($form_id == 'contact_message_stay_in_touch_form') {
  	 $form['actions']['preview']['#access'] = FALSE;
  	 $form['actions']['submit']['#value'] = 'IMAGE';
  	 $form['field_email']['widget']['0']['value']['#placeholder'] = 'Subscribe our newsletter';
  	 $form['field_email']['widget']['0']['value']['#title'] = FALSE;

  // dsm($form);
  }
}